apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: sample-errors
  namespace: argocd
spec:
  generators:
  - pullRequest:
      github:
        owner: hypertestco
        repo: sample-errors
        tokenRef:
           secretName: github-token
           key: token
        # labels:
        # - preview
      requeueAfterSeconds: 30
  template:
    metadata:
      name: 'sample-errors-{{branch}}'
    spec:
      source:
        repoURL: 'https://github.com/hypertestco/sample-errors'
        targetRevision: 'HEAD'
        path: sample-errors/
        helm:
          parameters:
          # - name: "image.repository"
          #   value: "nehahypertest/sample-errors"
          # - name: "image.tag"
          #   value: '{{branch}}-{{head_sha}}'
          - name: "ingress.hosts[0].host"
            value: "{{branch}}.hypertest"
          - name: "ingress.hosts[0].paths[0].path"
            value: "/"
          - name: "ingress.hosts[0].paths[0].pathType"
            value: "ImplementationSpecific"
      project: default  
      syncPolicy:
        automated:
          prune: true
          selfHeal: false
        syncOptions:
          - CreateNamespace=true
      destination:
        server: https://kubernetes.default.svc
        namespace: 'sample-errors'