apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sample-errors-application
  namespace: argocd
spec:
  project: default
  source:     
    repoURL: https://github.com/neha-hypertest/sample-errors
    targetRevision: HEAD
    path: sample-errors
    helm:
      parameters:
      # - name: "image.repository"
      #   value: "nehahypertest/sample-errors"
      - name: "image.tag"
        value: 'main'
      - name: "ingress.hosts[0].host"
        value: "main.hypertest.demo"
      - name: "ingress.hosts[0].paths[0].path"
        value: "/"
      - name: "ingress.hosts[0].paths[0].pathType"
        value: "ImplementationSpecific"
  destination: 
    server: https://kubernetes.default.svc
    namespace: sample-errors

  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
