name: Close Pull Requests after 7 days

on:
  schedule:
    - cron: '0 0 * * *' # Run at midnight every day

  workflow_dispatch:


jobs:
  close_pull_requests:
    runs-on: ubuntu-latest
    steps:

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Close Pull Requests
        run: |
          pull_requests=$(curl -H "Authorization: Bearer ${{ secrets.PAT }}" -H "Accept: application/vnd.github.v3+json" -s "https://api.github.com/repos/${{ github.repository }}/pulls")
          for pr in $(echo "${pull_requests}" | jq -r '.[] | select(.head.user.login != "hypertestco") | select((now - (.updated_at | fromdateiso8601)) > 604800) | .number'); do
            echo $pr
            curl -s -X POST -H "Authorization: Bearer ${{ secrets.PAT }}" "https://api.github.com/repos/${{ github.repository }}/pulls/$pr" -d '{"state": "closed"}'
          done
