name: Create Application
on:
  pull_request_target:
    types: [opened, synchronize, reopened, edited]
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  HT_BASE_URL: 'http://ht-sample-errors.hypertest.demo-k8s.hypertest.co'
  HT_API_TOKEN: ${{ secrets.HT_API_TOKEN }}
  HT_COMMIT_HASH: '${{ github.event.pull_request.head.sha }}' ## required because checkout creates a detached commit with a different sha
  BRANCH_NAME: ${{ github.repository_owner }}-${{ github.head_ref }}
  IMAGE_NAME: sample-errors
  IMAGE_TAG: ${{ github.repository_owner }}-${{ github.head_ref }}-${{ github.event.pull_request.head.sha }}


jobs:
  build:  
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v3
