name: Rebuild HyperTest Cli binary Cache
on:
  schedule:
    - cron: '0 0 */6 * *' # Run at midnight every 6th day of month
  workflow_dispatch:
jobs:
  rebuild-cache:
    if: github.ref_name == 'main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Delete existing cache
        run: |
          echo "============== gh-actions install ===================="
          gh extension install actions/gh-actions-cache
          echo "============== Cache Delete ===================="
          gh actions-cache delete ht-cli-cache --confirm || true
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Cache node modules
        id: cache-npm
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: 'ht-cli.tar.xz'
          key: ht-cli-cache
      - name: Download HyperTest Cli
        run: wget -O ht-cli.tar.xz https://hypertest-binaries-1.s3.ap-south-1.amazonaws.com/ht-cli/ht-cli-latest.tar.xz -nv 
